# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Hero
  description: Hero block
  icon: pending
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  preheader: ""
  header: ""
  description: ""
  background_image: ""
  hero_column_image: ""
  cta_button:
    _bookshop_name: button
    button_text: Click me

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  preheader: Hero page
  header: Hero
  description: "Sample description text"
  background_image: ""
  hero_column_image: ""
  cta_button:
    _bookshop_name: button
    button_text: Click me

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
