# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Hero
  description: Main page Hero block
  icon: title
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  preheading: "Eye"
  hero_text: "Hello World from the hero!"
  background_image: ""
  cta_button: [bookshop:button!]

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  preheading: Preview preheading
  hero_text: Preview hero text
  background_image: ""
  cta_button: [bookshop:button!]

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
