# Metadata about this component, to be used in the CMS
spec:
  structures: [content_blocks]
  label: "Hero"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  hero_text: "Hello World from the hero!"
  cta_button: [bookshop:button!]
  column_components:
    [
      bookshop:structure:content_blocks!(hero),
      bookshop:structure:content_blocks!(button)
    ]

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
