baseURL = ' https://charming-tuba.cloudvent.net'
languageCode = 'en-us'
title = 'Hackday 2022 - Hugo Bookshop'
theme = "hackday"

[module]
replacements = "components.local -> ../component-library"

[[module.imports]]
path = 'components.local'

[[module.imports]]
path = 'github.com/cloudcannon/bookshop/hugo/v3'
