# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Content Two Column
  description: Two column content block with text and image
  icon: pending
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  preheader: ""
  header: ""
  description: ""
  content_column_image: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  preheader: preheader
  header: Content Header
  description: "Sample description text"
  content_column_image: ""

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
